base:
  base_score: null
  booster: null
  callbacks: null
  colsample_bylevel: null
  colsample_bynode: null
  colsample_bytree: null
  device: gpu
  early_stopping_rounds: 5
  enable_categorical: false
  eval_metric: null
  feature_types: null
  gamma: null
  grow_policy: null
  importance_type: null
  interaction_constraints: null
  learning_rate: 0.03
  max_bin: null
  max_cat_threshold: null
  max_cat_to_onehot: null
  max_delta_step: null
  max_depth: 5
  max_leaves: null
  min_child_weight: 2
  missing: .nan
  monotone_constraints: null
  multi_strategy: null
  n_estimators: 250
  n_jobs: null
  num_class: 7
  num_parallel_tree: null
  objective: multi:softprob
  random_state: 0
  reg_alpha: null
  reg_lambda: null
  sampling_method: null
  scale_pos_weight: null
  subsample: null
  tree_method: hist
  validate_parameters: null
  verbosity: 0
coarse_solvent:
  base_score: null
  booster: null
  callbacks: null
  colsample_bylevel: null
  colsample_bynode: null
  colsample_bytree: null
  device: gpu
  early_stopping_rounds: 5
  enable_categorical: false
  eval_metric: null
  feature_types: null
  gamma: null
  grow_policy: null
  importance_type: null
  interaction_constraints: null
  learning_rate: 0.03
  max_bin: null
  max_cat_threshold: null
  max_cat_to_onehot: null
  max_delta_step: null
  max_depth: 12
  max_leaves: null
  min_child_weight: 5
  missing: .nan
  monotone_constraints: null
  multi_strategy: null
  n_estimators: 350
  n_jobs: null
  num_class: 6
  num_parallel_tree: null
  objective: multi:softprob
  random_state: 0
  reg_alpha: null
  reg_lambda: null
  sampling_method: null
  scale_pos_weight: null
  subsample: null
  tree_method: hist
  validate_parameters: null
  verbosity: 0
