# lightning.pytorch==2.4.0
seed_everything: true
trainer:
  accelerator: auto
  strategy: auto
  devices: auto
  num_nodes: 1
  precision: null
  logger:
  - class_path: lightning.pytorch.loggers.WandbLogger
    init_args:
      save_dir: logs
      project: morgan_mtnn
      entity: matt_ball30-university-of-strasbourg
  callbacks: null
  fast_dev_run: false
  max_epochs: 35
  deterministic: true
  enable_checkpointing: true
  enable_progress_bar: true
  enable_model_summary: true
model:
  task_head_params:
    exact_solvent:
      output_size: 322
      loss_fn: 
        class_path: torch.nn.CrossEntropyLoss
      hidden_layers: null
    exact_base:
      output_size: 63
      loss_fn: 
        class_path: torch.nn.CrossEntropyLoss
      hidden_layers: null
  shared_layers:
  - 512
  activation_fn:
    class_path: torch.nn.ReLU
  dropout_rate: 0.17485954160216197
  learning_rate: 0.0025159770060693507
  multilabel_mask:
  - false
  - false
  metric_save_dir: null
  use_likelihood_ranking: false
data:
  data_path: data/parsed_jacs_data/splits/data_seed_1.csv
  target_cols:
  - coarse_solvent
  - base
  fp_save_path: null
  fp_length: 512
  fp_radius: 3
  precompute_fps: true
  reload_fps: false
  batch_size: 20
  num_workers: 4
optimizer: null
lr_scheduler: null
data: data.MorganFPReactionDataModule
checkpoint_config:
  dirpath: null
  filename: best_val_loss
  monitor: val_loss
  verbose: true
  save_last: false
  save_top_k: 1
  save_weights_only: false
  mode: min
  auto_insert_metric_name: false
  enable_version_counter: true
early_stopping_config:
  monitor: val_loss
  min_delta: 0.0
  patience: 3
  verbose: false
  mode: min
  strict: true
  check_finite: true
  stopping_threshold: null
  divergence_threshold: null
  check_on_train_epoch_end: null
  log_rank_zero_only: false

