base:
  bootstrap: true
  ccp_alpha: 0.0
  class_weight: null
  criterion: gini
  max_depth: 70
  max_features: sqrt
  max_leaf_nodes: null
  max_samples: null
  min_impurity_decrease: 0.0
  min_samples_leaf: 1
  min_samples_split: 10
  min_weight_fraction_leaf: 0.0
  monotonic_cst: null
  n_estimators: 400
  n_jobs: null
  oob_score: false
  random_state: 0
  verbose: 0
  warm_start: false
coarse_solvent:
  bootstrap: true
  ccp_alpha: 0.0
  class_weight: null
  criterion: gini
  max_depth: 80
  max_features: sqrt
  max_leaf_nodes: null
  max_samples: null
  min_impurity_decrease: 0.0
  min_samples_leaf: 1
  min_samples_split: 4
  min_weight_fraction_leaf: 0.0
  monotonic_cst: null
  n_estimators: 400
  n_jobs: null
  oob_score: false
  random_state: 0
  verbose: 0
  warm_start: false
